name: Build APK

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    # یہاں ہم نے ورژن کو بالکل لیٹسٹ کر دیا ہے تاکہ Node 24 کا ایرر نہ آئے
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libtool pkg-config autoconf automake libffi-dev ccache gettext git zip unzip
        pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Build Android APK with Buildozer
      run: |
        export ANDROID_SDK_ROOT=$ANDROID_HOME
        export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk/25.2.9519653
        yes | buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
